BoardPick/BoardPick-server

- src/main/java/com/swyp/boardpick/domain/BoardGame.java
- src/main/java/com/swyp/boardpick/domain/BoardGameCategory.java
- src/main/java/com/swyp/boardpick/domain/Category.java
- src/main/java/com/swyp/boardpick/domain/Choice.java
- src/main/java/com/swyp/boardpick/domain/Emotion.java
- src/main/java/com/swyp/boardpick/domain/Post.java
- src/main/java/com/swyp/boardpick/domain/Review.java
- src/main/java/com/swyp/boardpick/domain/ReviewChoice.java
- src/main/java/com/swyp/boardpick/domain/Role.java
- src/main/java/com/swyp/boardpick/domain/User.java
- src/main/java/com/swyp/boardpick/domain/UserBoardGame.java
- src/main/java/com/swyp/boardpick/dto/response/BoardGameDto.java
close #3 Entity 추가
Entity 추가해서 DB에 반영했습니다.
> feat: Entity 추가

- src/main/java/com/swyp/boardpick/controller/BoardGameController.java
- src/main/java/com/swyp/boardpick/domain/BoardGame.java
- src/main/java/com/swyp/boardpick/service/BoardGameRecommendationService.java
- src/main/java/com/swyp/boardpick/service/implement/SimpleBoardGameRecommendationService.java
Closes BoardPick/BoardPick-server#5
- 유추 추천 보드게임 기능
- 일단 전체 보드게임에서 최대 10개를 랜덤으로 뽑아 추천하는 구현체로 넣어놓음
- 추후에 뷰 횟수 기반으로 추천하는 구현체 개발
> Feature(#5) : 추천 보드게임 구현

- src/main/java/com/swyp/boardpick/controller/BoardGameController.java
- src/main/java/com/swyp/boardpick/domain/BoardGameCategory.java
- src/main/java/com/swyp/boardpick/domain/Category.java
- src/main/java/com/swyp/boardpick/dto/response/BoardGameDto.java
- src/main/java/com/swyp/boardpick/repository/BoardGameCategoryRepository.java
- src/main/java/com/swyp/boardpick/repository/CategoryRepository.java
- src/main/java/com/swyp/boardpick/service/implement/BoardGameService.java
close #11 
`/api/boardgames?category=카드&page=0&size=10` 카테고리 정보와 페이지 정보를 같이 요청하면 보드게임 조회 가능
```Json
[
{
"id": 1,
"thumbnailUrl": "https://cf.geekdo-images.com/8kl6m6m_unthBPw9SxoDQQ__thumb/img/vK6rBE3ZjolzG6jEVxJj49MBIc4=/fit-in/200x150/filters:strip_icc()/pic6973677.png",
"imageUrl": "https://cf.geekdo-images.com/8kl6m6m_unthBPw9SxoDQQ__original/img/FtecAcFxPelZCfbWhZlo85uF2Rg=/0x0/filters:format(png)/pic6973677.png",
"name": "셀레스티아1",
"description": "예시용 설명",
"rating": 0.0,
"ratingCount": 0
},
{
"id": 2,
"thumbnailUrl": "https://cf.geekdo-images.com/8kl6m6m_unthBPw9SxoDQQ__thumb/img/vK6rBE3ZjolzG6jEVxJj49MBIc4=/fit-in/200x150/filters:strip_icc()/pic6973677.png",
"imageUrl": "https://cf.geekdo-images.com/8kl6m6m_unthBPw9SxoDQQ__original/img/FtecAcFxPelZCfbWhZlo85uF2Rg=/0x0/filters:format( …
```
> Feature: 카테고리별 보드게임 조회

- src/main/java/com/swyp/boardpick/domain/UserBoardGame.java
- src/main/java/com/swyp/boardpick/service/implement/UserBoardGameService.java
close #16 
여기에 작성하세요
DB에서 `user_board_game` 테이블에 date 칼럼을 추가했습니다. 준성님이 작업해주신 거에 이어서 작업했습니다
```Java
// 좋아요
else {
UserBoardGame userBoardGame = new UserBoardGame();
User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("User not found"));
BoardGame boardGame = boardGameRepository.findById(boardGameId).orElseThrow(() -> new RuntimeException("BoardGame not found"));
userBoardGame.setUser(user);
userBoardGame.setBoardGame(boardGame);
// 저장될 때 날짜 같이 저장
userBoardGame.setDate(new Date());
userBoardGameRepository.save(userBoardGame);
return true;
}
```
> Feat: myPick에 date 속성 추가

- src/main/java/com/swyp/boardpick/controller/UserBoardGameController.java
- src/main/java/com/swyp/boardpick/domain/BoardGameTag.java
- src/main/java/com/swyp/boardpick/dto/response/BoardGameDto.java
- src/main/java/com/swyp/boardpick/repository/BoardGameTagRepository.java
- src/main/java/com/swyp/boardpick/repository/TagRepository.java
- src/main/java/com/swyp/boardpick/repository/UserRepository.java
- src/main/java/com/swyp/boardpick/service/implement/BoardGameService.java
- src/main/java/com/swyp/boardpick/service/implement/UserService.java
close #13 
User가 Pick 한 보드게임들 List로 반환했습니다.
```Json
[
{
"id": 1,
"thumbnailUrl": "https://cf.geekdo-images.com/8kl6m6m_unthBPw9SxoDQQ__thumb/img/vK6rBE3ZjolzG6jEVxJj49MBIc4=/fit-in/200x150/filters:strip_icc()/pic6973677.png",
"imageUrl": "https://cf.geekdo-images.com/8kl6m6m_unthBPw9SxoDQQ__original/img/FtecAcFxPelZCfbWhZlo85uF2Rg=/0x0/filters:format(png)/pic6973677.png",
"name": "셀레스티아1",
"description": "예시용 설명",
"rating": 0.0,
"ratingCount": 0
},
{
"id": 2,
"thumbnailUrl": "https://cf.geekdo-images.com/8kl6m6m_unthBPw9SxoDQQ__thumb/img/vK6rBE3ZjolzG6jEVxJj49MBIc4=/fit-in/200x150/filters:strip_icc()/pic6973677.png",
"imageUrl": "https://cf.geekdo-images.com/8kl6m6m_unthBPw9SxoDQQ__original/img/FtecAcFxPelZCfbWhZlo85uF2Rg=/0x0/filters:format(png)/pic6973677.png",
"name": "셀레스티아2", …
```
> Feat: MyPickList 보드게임 조회하기

- src/main/java/com/swyp/boardpick/controller/BoardGameController.java
- src/main/java/com/swyp/boardpick/repository/BoardGameRepository.java
- src/main/java/com/swyp/boardpick/service/implement/BoardGameService.java
close #15 
```Java
@Query("SELECT bg FROM BoardGame bg LEFT JOIN bg.userBoardGames ubg " +
"WHERE ubg.date = CURRENT_DATE " +
"GROUP BY bg " +
"ORDER BY COUNT(ubg) DESC")
Page<BoardGame> findByPickCountDescForToday(Pageable pageable);
```
쿼리로 오늘의 픽 보드게임을 조회해 왔습니다.
- 오늘 날짜와 같을 때
- 픽 많이 받은 수로 정렬해서 조회
10개 받아오는 건 pagination 써서 10개를 가져오도록 했습니다.
> Feat: 오늘의 픽 구현

- .github/workflows/cicd.yml
- src/main/java/com/swyp/boardpick/handler/OAuth2SuccessHandler.java
서버 환경에서 로그인 테스트
- 리다이렉션 주소 프론트엔드 주소로 연결 `frontend.url=https://boardpick.netlify.app`
gpt가 이상한 url 알려줘서 1시간 30분 날림
> Chore: 서버환경에서 로그인 테스트 완료

- src/main/java/com/swyp/boardpick/config/WebSecurityConfig.java
- src/main/java/com/swyp/boardpick/controller/Controller.java
- src/main/java/com/swyp/boardpick/controller/UserBoardGameController.java
- src/main/java/com/swyp/boardpick/controller/UserController.java
- src/main/java/com/swyp/boardpick/domain/Uri.java
- src/main/java/com/swyp/boardpick/dto/response/UserDto.java
- src/main/java/com/swyp/boardpick/service/implement/UserBoardGameService.java
- src/main/java/com/swyp/boardpick/service/implement/UserService.java
- 로그인한 유저 정보 가져오기
- 로그인한 유저에 대해 내정보 가져오기 API 구현
- 비로그인 유저가 내정보나 myPick 접속 시 로그인 페이지로 redirection 처리
> Feature: 유저 정보 가져오기 구현

- src/main/java/com/swyp/boardpick/domain/BoardGame.java
- src/main/java/com/swyp/boardpick/dto/response/BoardGameDto.java
`BoardGame`, `BoardGameDto`에 `private String extraVideo` 추가
- `BoardGame`, `BoardGameDto`에 `private String extraVideo` 추가
- rebuild
> Feature: BoardGame에 extraVideo 추가

- .github/workflows/cicd.yml
workflow.yml에 dev 브랜치에 대한 trigger 삭제
```
on:
push:
branches:
- main
pull_request:
branches:
- main
```
여기 원래 dev 브랜치도 있었는데 삭제
> Chore: workflow.yml에 dev 브랜치에 대한 trigger 삭제

- .github/workflows/cicd.yml
- src/main/java/com/swyp/boardpick/domain/BoardGame.java
- src/main/java/com/swyp/boardpick/utils/BoardGameEntityListener.java
BoardGame Rule, BoardGame ExtraVideo들에 대해 embed 형식으로 변환
- DB에 있는 BoardGame Rule, BoardGame ExtraVideo들에 대해 embed 형식으로 변환해서 업데이트
- `@EntityListeners`와 `@PrePersist`, `@PreUpdate`를 통해 
`BoardGame Entity`가 저장되기전과 업데이트 되기 전에 formatting 전처리
> Feature: YouTube URL Formatting

- src/main/java/com/swyp/boardpick/domain/Difficulty.java
- src/main/java/com/swyp/boardpick/dto/response/BoardGameDto.java
- src/main/java/com/swyp/boardpick/service/implement/BoardGameService.java
보드게임 Dto에서 
difficulty와 boardGameCategory를 String으로 변경
```java
public class BoardGameDto {
private String difficulty;
private List<String> boardGameCategories;
...
}
private BoardGameDto convertToDto(BoardGame boardGame) {
String difficulty = convertDifficulty(boardGame.getDifficulty()).getDescription();
List<String> boardGameCategories = boardGame.getBoardGameCategories()
.stream().map(boardGameCategory -> boardGameCategory.getCategory().getType())
.toList();
...
return new BoardGameDto(...);
}
```
> Feature: String으로 응답

- .github/workflows/cicd.yml
- src/main/java/com/swyp/boardpick/config/WebSecurityConfig.java
- src/main/java/com/swyp/boardpick/controller/UserBoardGameController.java
- src/main/java/com/swyp/boardpick/controller/UserController.java
- src/main/java/com/swyp/boardpick/domain/Uri.java
- src/main/java/com/swyp/boardpick/handler/OAuth2SuccessHandler.java
- credential 설정
- 유저 비로그인시 302로 리다이렉트 시키던걸 401 unauthorized로 변경
```java
if (principal == null) {
//            URI uri = URI.create(Uri.LOGIN_PAGE.getDescription());
//            return ResponseEntity.status(HttpStatus.FOUND).location(uri).build();
return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
}
```
> Fix: cors configs

- .github/workflows/cicd.yml
- src/main/java/com/swyp/boardpick/config/WebSecurityConfig.java
- src/main/java/com/swyp/boardpick/controller/UserBoardGameController.java
- src/main/java/com/swyp/boardpick/controller/UserController.java
- src/main/java/com/swyp/boardpick/dto/response/JwtDto.java
- src/main/java/com/swyp/boardpick/handler/OAuth2SuccessHandler.java
- src/main/java/com/swyp/boardpick/provider/JwtProvider.java
SecurityConfig 변경
- `/api/pick/**`, `/api/user/**`에 대해 `.authenticated()` 설정
- session 기반 인증 방식에서 jwt 기반 인증 방식으로 변경.
- `Controller`에서 `@AuthenticationPrincipal` -> `Authentication`으로 변경
> Fix: security config 수정. session 인증 방식 -> jwt 기반 인증

- src/main/java/com/swyp/boardpick/controller/BoardGameController.java
- src/main/java/com/swyp/boardpick/repository/BoardGameRepository.java
- src/main/java/com/swyp/boardpick/service/implement/BoardGameService.java
여기에 작성하세요
close #41 
1. 난이도 제일 쉬운 보드게임 10개
2. 2인 게임 10개
3. 인원이 많이 필요한 게임 10개
> Feat: 상위 10개 항목 조회하는 API 추가

- src/main/java/com/swyp/boardpick/repository/BoardGameRepository.java
today-pick에서 날짜 비교할 때 Date Type이 달라서 잘 비교가 안 되고 있었음
ubg.date가 시간까지 포함된 정보(DATETIME)라 
DATE()로 일자 정보만 가져와서 비교하는 걸로 수정
`"WHERE ubg.date = CURRENT_DATE "` -> `"WHERE DATE(ubg.date) = CURRENT_DATE "`
> Fix: today-pick 수정

- src/main/java/com/swyp/boardpick/repository/BoardGameRepository.java
인원이 많이 필요한 보드게임 10개 반환
인원 수 많은 보드게임 10개 반환하는 API 수정
> Fix: 인원수 많은 보드게임 쿼리 수정

- src/main/java/com/swyp/boardpick/controller/BoardGameController.java
- src/main/java/com/swyp/boardpick/repository/BoardGameRepository.java
- src/main/java/com/swyp/boardpick/service/implement/BoardGameService.java
OO과 비슷한 보드게임
- 특정 보드게임과 카테고리적으로 유사한 보드게임 리스트 반환
- 자기 자신은 제외
> Feature: similar board game

- src/main/java/com/swyp/boardpick/service/implement/OAuth2UserServiceImplement.java
- OAuth2 프로필 정보 변경 시 업데이트 되게 수정
- nickname이라 profile 항목 없을 시 핸들링 로직 추가
```java
//            if (userRepository.findByCode(userCode).isPresent())
//                return new CustomOAuth2User(userCode, authorities);
user = new User(userCode);
Map<String, Object> attributes = oAuth2User.getAttributes();
String nickname = Optional.ofNullable(attributes)
.map(attrs -> attrs.get("kakao_account"))
.filter(kakaoAccount -> kakaoAccount instanceof Map)
.map(kakaoAccount -> ((Map<?, ?>) kakaoAccount).get("profile"))
.filter(profile -> profile instanceof Map)
.map(profile -> ((Map<?, ?>) profile).get("nickname"))
.filter(nicknameObj -> nicknameObj instanceof String)
.map(nicknameObj -> (String) nicknameObj)
.orElse("보드픽");
String profileImage = Optional.ofNullable(attributes)
.map(attrs -> …
```
> Fix: 프로필 정보 변경 시 업데이트 되게 수정

- src/main/java/com/swyp/boardpick/controller/BoardGameController.java
- src/main/java/com/swyp/boardpick/controller/UserBoardGameController.java
- src/main/java/com/swyp/boardpick/dto/response/BoardGameDto.java
- src/main/java/com/swyp/boardpick/service/implement/BoardGameService.java
- src/main/java/com/swyp/boardpick/service/implement/UserBoardGameService.java
- src/main/java/com/swyp/boardpick/service/implement/UserService.java
close #49 
기존 간단 버전과 상세 버전으로 제공 되던 BoardGameDto를 상세 버전 하나로 통합
간단 버전을 사용중이던 곳에서 상세버전으로 변경
> Refactor: BoardGameDto 통일

- src/main/java/com/swyp/boardpick/service/implement/OAuth2UserServiceImplement.java
업데이트 그래도 안 되던 문제 진짜 해결
이미 유저가 있으면 update, 없으면 Insert하게 변경
> Fix: 업데이트 안 되던 문제 해결

- src/main/java/com/swyp/boardpick/handler/OAuth2SuccessHandler.java
- src/main/java/com/swyp/boardpick/repository/UserBoardGameRepository.java
- src/main/java/com/swyp/boardpick/service/implement/UserBoardGameService.java
mypick list가 최신순으로 정렬되게 수정
```java
List<UserBoardGame> findByUserIdOrderByDateDesc(Long userId);
```
추가
> Fix: mypick list가 최신순으로 정렬되게 수정

- src/main/java/com/swyp/boardpick/controller/BoardGameController.java
- src/main/java/com/swyp/boardpick/repository/BoardGameRepository.java
- src/main/java/com/swyp/boardpick/repository/UserBoardGameRepository.java
- src/main/java/com/swyp/boardpick/service/implement/BoardGameService.java
- src/main/java/com/swyp/boardpick/service/implement/UserBoardGameService.java
close #51 
- 유저 픽 기반 추천 보드게임 기능 구현
- 유저가 픽한 게임들의 카테고리들을 점수 매겨서 전체 보드게임에서 카테고리 점수를 높게 받은 보드게임 순으로 최대 10개 반환
- 10개 미만 시 랜덤 보드게임으로 채워 넣음
- 순회 로직이 많아 `@Cacheable` 도입
- pick 발생 시 cache 초기화
- 비로그인 or pick한 게임이 없을 시에도 랜덤 보드게임 10개 반환
- "이런 보드게임은 어떠세요?" 구현
- 전체 누적 픽 기준으로 상위 10개 반환
```java
@GetMapping("/recs")
public ResponseEntity<List<BoardGameDto>> getRecommendations(Authentication principal) {
if (principal == null) {
return ResponseEntity.ok(
boardGameService.convertToDotListForAnonymous(
boardGameService.getRandomBoardGames()
));
}
Long userId = userService.getUserId(principal.getName());
List<BoardGame> recommendedBoardGames = boardGameService.getRecommendationBoardGamesByUser(userId);
if (recommendedBoardGames.size() < 10) {
List<BoardGame> randomBoardGames = …
```
> Feature: pick based recommendation & suggestion

- src/main/java/com/swyp/boardpick/controller/UserBoardGameController.java
보드게임에 대한 picked 정보 반환하는 API 구현 
URL: `api/pick/get/{boardgame_id}` 
```java
@GetMapping("/get/{boardGameId}")
public ResponseEntity<?> getPicked(@PathVariable("boardGameId") Long boardGameId, Authentication principal) {
if (principal == null)
return ResponseEntity.ok().body(Map.of("picked", false));
Long userId = userService.getUserId(principal.getName());
boolean picked = userBoardGameService.getPicked(userId, boardGameId);
return ResponseEntity.ok().body(Map.of("picked", picked));
}
```
=
> Feature: 보드게임에 대한 picked 정보 반환하는 API 구현

- src/main/java/com/swyp/boardpick/handler/OAuth2SuccessHandler.java
- src/main/java/com/swyp/boardpick/repository/BoardGameRepository.java
- src/main/java/com/swyp/boardpick/service/implement/BoardGameService.java
오늘의 픽에서 픽수가 같을 시 이름 순으로 정렬
```java
@Query("SELECT bg FROM BoardGame bg LEFT JOIN bg.userBoardGames ubg " +
"WHERE DATE(ubg.date) = CURRENT_DATE " +
"GROUP BY bg " +
"ORDER BY COUNT(ubg) DESC, bg.name ASC")
Page<BoardGame> findByPickCountDescForToday(Pageable pageable);
```
> Feature: 오늘의 픽에서 픽수가 같을 시 이름 순으로 정렬

- .github/workflows/cicd.yml
- src/main/java/com/swyp/boardpick/controller/UserBoardGameController.java
- src/main/java/com/swyp/boardpick/service/implement/UserBoardGameService.java
pick한 보드게임의 id 리스트 반환
```json
[
39,
11,
2,
19
]
```
pick한 보드게임의 id값들을 리스트로 반환하는 API 구현
> Feature: pick한 보드게임의 id 리스트 반환

- src/main/java/com/swyp/boardpick/controller/BoardGameController.java
- src/main/java/com/swyp/boardpick/controller/UserBoardGameController.java
- src/main/java/com/swyp/boardpick/domain/UserBoardGame.java
UserBoadGame의 boardGameId 칼럼에 대한 db-index 추가
getPopularBoardGames()의 조회 성능을 올리기 위한 db-index 추가
> Feature: UserBoadGame의 boardGameId 칼럼에 대한 db-index 추가
